version: '3.8'

services:
  santis-api:
    build: .
    container_name: santis-core-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      # Mount the current directory to enable live-reloading (optional) and persistent data
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=production
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
